### ISSUE TITLE
json: cannot unmarshal object into Go value of type *net.IPNet

### ISSUE THREAD

**Issue by fufuok** [goccy/go-json#170]
```
package main

import (
	_ "encoding/json" // ok
	"fmt"
	"net"

	"github.com/goccy/go-json" // panic
)

type tConf struct {
	WhiteListConf []string `json:"white_list"`
	WhiteList     map[*net.IPNet]struct{}
}

func main() {
	var conf tConf
	js := `{"white_list": ["1.1.1.1", "2.2.2.0/24"]}`
	if err := json.Unmarshal([]byte(js), &conf); err != nil {
		panic(err)
	}
	fmt.Println(conf)
}

// panic: json: cannot unmarshal object into Go value of type *net.IPNet
```

**Comment by goccy** [comment]
Thank you for your report. I found that this problem was caused by the difference of design between `go-json` and `encoding/json` .  `map[*net.IPNet]struct{}` is actually an invalid type, but `go-json` will check in advance regardless of the data to be decoded, so an error will occur. Since `encoding/json` dynamically type-checks when evaluating data, no error will occur if there is no data corresponding to the invalid type.

This will be fixed, but please use `json:"-"` as a workaround .

**Comment by fufuok** [comment]
Thank you. I see.

**Comment by fufuok** [comment]
Thanks for the great library, which has been used in production.

Hope to be repaired and 100% compatible. Thanks!

**Comment by goccy** [comment]
Wow, Thank you for using !
